### ISSUE TITLE
The app is not "optimized" for the iPhone 6

### ISSUE THREAD

**Issue by gkrol-zermelo** [zermelo-software/zermelo-app#13]
It seems we can do so and it will look slightly nicer. This may just be a configuration change.

**Comment by Boltgolt** [comment]
The app is not "optimised" for **any** phone or OS because you're using phonegap. Focussing on the iPhone 6 seems a bit weird.

**Comment by gkrol-zermelo** [comment]
Sure, but we may be able to get slightly better results when we allow PhoneGap to go into "iPhone 6" mode. Better resolution or a nicer keyboard for entering the code for example. Just something to investigate.

**Comment by Thymo-** [comment]
Why is PhoneGap being used anyways? Using that to port apps to Java and Swift for Android and IOS will just cause huge performance issues (which is proven by the extremely low performance compared to other apps on a flagship device).

Please don't tell me the only reason is because of saving money so only one dev is needed for one language instead of one or multiple for two native apps.

**Comment by bramhaag** [comment]
I argee, but having to update 2 different apps at the same time costs loads of time. An alternative could be to use C# for backend and use the native UI frontend (info: http://youtu.be/GuzyVor2OvU), this works for Android, iOS and Windows phone. I'm not sure about the performance when you use C# for mobile devices, but I think that it can run without any hiccups. But I've always preferred programming languages like Java, C#, Swift, CPP etc. over JavaScript and HTML etc.

**Comment by Nickforall** [comment]
A few points why you shouldn't use phonegap

* HTML and JavaScript is not made for app development.
* You don't follow the design rules of the platform
* Using these languages takes unnecessary memory/storage because of the render engine
* Most people, including zermelo in my opinion, don’t seem to understand how web apps work. And only choose it because of cross platform compability.
* Native apps have way more functionailities, push notificiations for a timetable app would be amazing for instance.

Also, Zermelo doesn't seem to care much about design, the UI is horrible and slow. So I don't see why you would care about this iphone 6 issue. Instead of creating a web-app I would recommend to make a choice and create either a responsive website or native apps.

**Comment by gkrol-zermelo** [comment]
Welcome to the real world, in which there is never enough time (or money) to do everything absolutely perfectly. We know Phonegap/Cordova is a compromise. It was either Phonegap or just an Android app.

Please don't start a native/non native flame war here. If you want a native app you're free to build one yourself or use an existing one. Zermeloner (Android) seems to work well. For an iOS app you could try to contact the developer of "Rooster for Zermelo" and ask him to make it available for other schools.

**Comment by developingwild** [comment]
We are already creating an awesome Zermelo for android :) . We first used phonegap indeed, but later on we decided we wanted it to be written in Java. If you would like to know more, just send an mail to developingwild (at) gmail.com :)
Have a nice day,
Greetings,
Niels, Developing wild :)

**Comment by coollorenzo** [comment]
@gkrol-zermelo Do you know what happened to zermeloner? Because i can't find it anywhere both on github and the playstore it's deleted! Also the server backend he used is deleted! Just before my school switched to zportal :(

**Comment by gkrol-zermelo** [comment]
@coollorenzo It seems to be discontinued, perhaps you could contact @mehlon to see what's going on. If you're looking for apps or libraries you can take a look at http://developers.zermelo.nl

**Comment by Zermelo-Ulbe** [comment]
The layout for larger iDevices has been improved in version 1.3.0.

**Comment by mehlon** [comment]
@coollorenzo I have stopped maintaining the zermeloner project altogether and don't plan to pick it up again. The very final version of the app is here: https://drive.google.com/open?id=0B0kSAYCf96Uiem04bmRNNTJTMDQ : it should still be perfectly functional.

**Comment by coollorenzo** [comment]
@mehlon Wow your still alive :P Thanks it still works great! But are you on a different school? Because I was your classmate in transitional class and they used zermelo. I'm now on a different school and they also use zermelo.
