### ISSUE TITLE
Make it possible to show the schedule by lesson hour

### ISSUE THREAD

**Issue by developingwild** [zermelo-software/zermelo-app#26]
Please make an version where you can only see your schedule. Day by day, categorizing in school hours (for me its 1e hour (45 minutes) , second hour (again 45 minutes), etc.

**Comment by bramhaag** [comment]
Replacing the time in the schedule with school hours instead of 'normal' hours seems like a good idea to me, but the developers will face a problem since the amount of minutes in 1 school hour are different for most schools (e.g my school hours are 50 minutes). 

The only possible way of doing this which I can think of is by letting each school fill in the amount of minutes that they use for 1 school hour. An option to switch between normal hours and school hours would be greatly appreciated though.

**Comment by gkrol-zermelo** [comment]
The API exposes the fields startTimeSlot and endTimeSlot that gives the (one based) index of the lesson hour the lesson is planned at. The differences between schools are not an issue.

There is a problem with showing everything by time slot though: if there are special appointments (like exams) then those often don't fall right on the time slots. Here at Zermelo we've decided to just show everything by the start and end times for that reason. Also, for teachers that give lessons at different schools, the start times of the lessons may not be the same. This also goes for when a student needs to travel to another building.

Any suggestions on how to solve this problem are of course welcome.

**Comment by ko3st** [comment]
I would suggest leaving the apps functionality as it is and calling that the "full view" or "view all" or whatever. 

Then the tricky part comes, to build functionality in which to collapse all info, to show only the lessonhours with the most basic info in it. That basic view could be called "basic view" :-)

I think you  can dynamically build the basic view from the full  view, if you know the lessonhours length and the start of each lessonhour and the maximum number of lessons in one day. 

If there are teachers who travel to other buildings with the same lessonhours, but different starting times, then in those circumstances, I would suggest two different approaches:

1. Another variable should be available also, in order to compensate for the lessonhour on that second location compared to the  lessonhour of the first location, in regards to the actual clock time (in the 24 hours in each day). 

2. Perhaps a different background color per location would suffice in order to make the user aware to which timetable he/she is watching!

Anyway, if you are in basic view and you would like more info regarding a certain lesson (if available), then the app could easily show that info as if it were partial in "full view'' mode again, because that view has never left and is always available :-).

Please let me know what you think of my ideas.

**Comment by Zermelo-Ulbe** [comment]
A property startTimeSlotName has been added to the API. This saves us the trouble of estimating what the timeslots of a specific school/location are. This new property is used in the new day view to clearly display timeslots with each class.

I believe the new day view roughly coincides with the basic view @ko3st described above.

Appointments in the day view as well as the week view are tappable and link to a detail view of the chosen appointment.
